import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bundle the API into one self-contained serverless function.
 *
 * Vercel TRACES imports rather than bundling them, and Node's ESM loader needs
 * an explicit file extension for every relative import. Our server code uses
 * extensionless imports and the `@shared/*` alias, neither of which survives
 * that: the deployed function loaded and then died on
 * `Cannot find module '/var/task/server/app'`.
 *
 * So the application code is bundled inline here, while npm packages are left
 * as bare imports — those Vercel traces correctly, and bundling them would
 * break the ones that use dynamic requires (`pg` looking for `pg-native`).
 *
 * The output IS committed. Vercel discovers serverless functions from the
 * repository at checkout, before any build runs, so a generated `api/` file
 * is simply never seen — the deployment came up with no function at all and
 * every API route fell through to the SPA. CI rebuilds it and fails if the
 * committed copy has drifted, so it cannot go stale.
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

await build({
  entryPoints: [path.join(root, 'server', 'serverless.ts')],
  outfile: path.join(root, 'api', 'index.js'),

  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',

  // Application code inlined; dependencies left for the platform to trace.
  packages: 'external',

  // `@shared/*` only exists in tsconfig, so esbuild is told about it too.
  alias: { '@shared': path.join(root, 'shared') },

  sourcemap: false,
  minify: false,
  logLevel: 'info',

  banner: {
    js: [
      '// GENERATED by scripts/build-api.ts — do not edit.',
      '// Committed because Vercel discovers functions at checkout, before the build runs.',
      '// Regenerate with: npm run build:api',
    ].join('\n'),
  },
});

console.info('[build-api] api/index.js written');
