import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bundle the API into one self-contained serverless function.
 *
 * Vercel TRACES imports rather than bundling them, and Node's ESM loader needs
 * an explicit file extension for every relative import. Our server code uses
 * extensionless imports and the `@shared/*` alias, neither of which survives
 * that: the deployed function loaded and then died on
 * `Cannot find module '/var/task/server/app'`.
 *
 * So the application code is bundled inline here, while npm packages are left
 * as bare imports — those Vercel traces correctly, and bundling them would
 * break the ones that use dynamic requires (`pg` looking for `pg-native`).
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

await build({
  entryPoints: [path.join(root, 'server', 'serverless.ts')],
  outfile: path.join(root, 'api', 'index.js'),

  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',

  // Application code inlined; dependencies left for the platform to trace.
  packages: 'external',

  // `@shared/*` only exists in tsconfig, so esbuild is told about it too.
  alias: { '@shared': path.join(root, 'shared') },

  sourcemap: false,
  minify: false,
  logLevel: 'info',

  banner: {
    js: '// Generated by scripts/build-api.ts. Do not edit; do not commit.',
  },
});

console.info('[build-api] api/index.js written');
